# Site
title: 'The Society for Mathematical Biology Podcast Feed'
name: 'The Society for Mathematical Biology Podcast Feed'
description: 'The Society for Mathematical Biology - podcast RSS feed.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
url:     "http://smb.org/"

customvar: 				 "custom"


# Social Profiles
twitter_username:  SMB_MathBiology


# Build settings
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  
# Paginate
paginate: 10

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all abstracts
  - scope:
      path: "_abstracts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
    

      
    
# Syntax
markdown: kramdown
highlighter: rouge 
    
    
collections:
  pages:
    output: true
    permalink: /:title

# Exclude metadata and development time dependencies (like Grunt plugins)
# exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
