# Site
title: 'Biology in Numbers'
name: 'The Society for Mathematical Biology'
description: 'The Society for Mathematical Biology: the Biology in Numbers podcast'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
url:     "http://podcast.smb.org"

customvar: 				 "custom"


# Social Profiles
twitter_username:  SMB_MathBiology

email: "website@smb.org"
subtitle: "Biology in Numbers"
lang: en-us
author: The Society for Mathematical Biology
copyright: "CC-BY 4.0"


# Build settings
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  
# Paginate
paginate: 10

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all abstracts
  - scope:
      path: "_abstracts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
    

      
    
# Syntax
markdown: kramdown
highlighter: rouge 
    
    
collections:
  pages:
    output: true
    permalink: /:title

# Exclude metadata and development time dependencies (like Grunt plugins)
# exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
