name: Deploy to GitHub Pages
on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 6 * * 0'  # This cron expression schedules the workflow to run at 6 AM UTC every Sunday

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build the project
        run: |
          # Add your build commands here, e.g., npm install && npm run build
          echo "Building the project..."

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Change this to the directory of your built site

